micronaut:
  application:
    name: demo
  security:
    authentication: cookie
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
elasticsearch.httpHosts: '"http://localhost:9200,http://127.0.0.2:9200"'
redis.uri: redis://localhost
